# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11299\Desktop\other\try\facesystem\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 490)
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        Form.setFont(font)
        self.faceget = QtWidgets.QPushButton(Form)
        self.faceget.setGeometry(QtCore.QRect(30, 70, 191, 61))
        self.faceget.setObjectName("faceget")
        self.facetrain = QtWidgets.QPushButton(Form)
        self.facetrain.setGeometry(QtCore.QRect(30, 150, 191, 61))
        self.facetrain.setObjectName("facetrain")
        self.guestcheck = QtWidgets.QPushButton(Form)
        self.guestcheck.setGeometry(QtCore.QRect(20, 230, 111, 51))
        self.guestcheck.setObjectName("guestcheck")
        self.picture = QtWidgets.QPushButton(Form)
        self.picture.setGeometry(QtCore.QRect(30, 330, 191, 61))
        self.picture.setObjectName("picture")
        self.hostcheck = QtWidgets.QPushButton(Form)
        self.hostcheck.setGeometry(QtCore.QRect(30, 400, 191, 61))
        self.hostcheck.setObjectName("hostcheck")
        self.textEdityes = QtWidgets.QTextEdit(Form)
        self.textEdityes.setGeometry(QtCore.QRect(263, 63, 431, 301))
        self.textEdityes.setReadOnly(True)
        self.textEdityes.setObjectName("textEdityes")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 20, 151, 20))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(130, 230, 101, 51))
        self.comboBox.setObjectName("comboBox")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(275, 390, 411, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.chaxun = QtWidgets.QLineEdit(Form)
        self.chaxun.setGeometry(QtCore.QRect(60, 290, 131, 31))
        self.chaxun.setText("")
        self.chaxun.setObjectName("chaxun")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "管理员界面"))
        self.faceget.setText(_translate("Form", "人脸录入"))
        self.facetrain.setText(_translate("Form", "开始训练"))
        self.guestcheck.setText(_translate("Form", "访客信息查询"))
        self.picture.setText(_translate("Form", "图像检测(测验）"))
        self.hostcheck.setText(_translate("Form", "业主信息查询"))
        self.textEdityes.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'方正粗黑宋简体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">注意</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">人脸录入前请先输入个人信息，确保个人信息无误</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">在此显示查询结果</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700; font-style:italic;\">管理员界面</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'方正粗黑宋简体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">开发者：ddd</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">支持：ddd</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; text-decoration: underline;\">版本：0.0.2(测试)</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
